project:
  type: website

website:
  title: "pycamp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - current_event.qmd

format:
  html:
    css: styles.css
    theme: cosmo
    toc: true
