# Edición actual
PyCamp España es un fin de semana que incluye 4 días y 3 noches con pensión completa (desayuno, comida y cena) en Sevilla, España. Podrás programar las horas que quieras en ese proyecto o idea que querías codificar hace tanto tiempo y que no encontrabas el momento o lugar perfecto para hacerlo.

La entrada incluye:

Pensión completa: desayuno, comida y cena
Transporte directo desde Sevilla hasta el venue
Coffee break en intermedio de comidas: café, té, agua, snacks y frutas
Acceso a áreas verdes donde podrás relajarte o programar
Diversión: karaoke de charlas, juegos de mesa, ping pong y todo hobby que quieras compartir con nosotros
El lugar será de uso únicamente exclusivo para los asistentes al evento.


# Inscripción
Por ahora no hay inscripción abierta.
Subscríbete al Newsletter para recibir novedades aquí:


Del 30 de Abril al 3 de Mayo, 2026.
4 días, 3 noches (pensión completa)
300€
Comprar entrada

## Everyone is welcome
We apologize for the lack of translation, but we believe Google translation works quite well (see translated version). If you have any question don't hesitate in contact us! We are happy to help you and have you enjoying this event with us!
