version: 2

build:
  os: ubuntu-24.04
  tools:
    nodejs: "24"
  commands:
    - npm install
    - echo $READTHEDOCS_VERSION
    - echo $READTHEDOCS_CANONICAL_URL
    - ./node_modules/.bin/vite build --base $READTHEDOCS_CANONICAL_URL --outDir $READTHEDOCS_OUTPUT/html
