version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    nodejs: "16"
  commands:
    - npm install -g yarn
    - yarn install
    - yarn clean
    - yarn build-prod
    - mkdir --parents _readthedocs/html
    - mv dist/* _readthedocs/html/
