version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install quarto 
    - mkdir --parents _readthedocs/html
    - cd quarto-site
    - quarto render --output-dir ../_readthedocs/html/
